[package]
name = "cs-essentials"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cs_essentials"
path = "src/lib.rs"

[[bin]]
name = "cs_essentials"
path = "src/bin/main.rs"

[dependencies]
